### ISSUE TITLE
CIS-2: Blank screen on adding token with decimal string in metadata

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-browser-wallet#161]
**Bug Description**

If the decimals field in the metadata is a string instead of an integer, the browser wallet shows a blank screen.

**Steps to Reproduce**
1. Add a token where the metadata has `"decimals": "not a number"`

**Expected Result**
Not sure, but perhaps the token should be displayed with 0 decimals. A warning could also be shown.

**Actual Result**
Blank screen of death: 
<img width="142" alt="image" src="https://user-images.githubusercontent.com/5469652/200860719-93662ae8-39b5-46de-b980-fd43ef697a5b.png">

**Notes for reproducing**
I've created a modified version of our wCCD contract in which you can update the metadata URL via the `updateUrl` entrypoint. 

The module is deployed on testnet with reference:
`058bf1d66a6b8fc258faeac69d633a04fd74cf3832dcdbe7a1252e7b23b320fc`.

I've created a number of test metadata files on gist (see the different revisions). You need to click the `raw` button to get the actual file (and link) that should be passed to `updateUrl`.

https://gist.github.com/Bargsteen/e1ebac26ee47d601c7d816c0f839261c/b68d8cf91ad0d3f816fd1d679626bcebb20edfb7

**Versions**
- Software Version: 0.8.0
- OS: macOS
- Browser: Arc browser

**Comment by shjortConcordium** [comment]
Fixed in 0.8.1
