### ISSUE TITLE
Can't build browser wallet wCCD example on Windows

### ISSUE THREAD

**Issue by Radiokot** [Concordium/concordium-browser-wallet#311]
**Bug Description**
I'm trying to follow the build instruction in order to run the wCCD example, but the `yarn build` command fails.

**Steps to Reproduce**
- Clone the https://github.com/Concordium/concordium-browser-wallet repository
- Run `yarn` in the root directory, wait for all the dependencies to be installed
- Go to the `examples/wCCD` directory
- Run `yarn`, wait for all the dependencies to be installed
- Run `yarn build`

**Expected Result**
The app is built successfully and can be launched by `yarn start`

**Actual Result**
The build fails with the following error:
```
✘ [ERROR] Could not resolve "@concordium/browser-wallet-api-helpers"

    ../../node_modules/@concordium/wallet-connectors/dist/BrowserWallet.js:13:45:
      13 │ ..._wallet_api_helpers_1 = require("@concordium/browser-wallet-api-helpers");
         ╵                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@concordium/browser-wallet-api-helpers" as external to exclude
  it from the bundle, which will remove this error. You can also surround this "require"
  call with a try/catch block to handle this failure at run-time instead of bundle-time.
```
The build output contains the incomplete `index.html` file, which does nothing when started with `yarn start`

**Versions**
- Software Version: [a834753](https://github.com/Concordium/concordium-browser-wallet/commit/a83475322ee682bc2b9ec842fa9c38be6c1a5276)
- OS: Windows 10
- Browser: MS Edge
- Mobile device, if applicable: No

**Comment by Radiokot** [comment]
It turned out that in order to build the example, you have to first run `yarn build` in the `packages/browser-wallet-api-helpers` directory. Consider adding this step to the wCCD build guide.

**Comment by dg-concordium** [comment]
@shjortConcordium Readme in the BW also needs to be updated.
