### ISSUE TITLE
Syntax error: Unexpected token 'export' and can't resolve '@concordium/web-sdk'

### ISSUE THREAD

**Issue by arslanpixpel** [Concordium/concordium-browser-wallet#328]
**Bug Description**

I have an react application in which I've implemented concordium sdk it was working well but when I have started migrating it to nextjs it is not working and it throws a error called Syntax  Error: Unexpected token 'export' for concordium/browser-wallet-api-helpers package and can't resolve '@concordium/web-sdk' for @concordium/web-sdk package

![29aba9b1ef3c9130c3930cb0d2a6de33c383df65](https://github.com/Concordium/concordium-browser-wallet/assets/135733448/5313d9df-17a9-49e4-bae7-d23f49fc9e73)

![82e7ba2d3f720e83e8c9138dc046675f055b89a8](https://github.com/Concordium/concordium-browser-wallet/assets/135733448/30b3a8d0-d1f0-4d8e-af80-61c25f5aa588)

**Comment by soerenbf** [comment]
A side note, this should have nothing to do with the browser wallet repository though. But as I wrote in my previous comment, we are aware of the inconvenience of having to do this workaround, so if the workaround works there is no need to create an issue for this.

For reference, here is the issue:
https://github.com/Concordium/concordium-node-sdk-js/issues/112

**Comment by shjortConcordium** [comment]
Nothing to do with the wallet.
