### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split').

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-browser-wallet#437]
**Bug Description**
If I try to set u8 value on testbench, I get an error. The same test case works with BW 1.4.1.

**Steps to Reproduce**
1. Connect bw 1.4.2 to test bench.
2.Don't add any parameters, set u8 value.

**Expected Result**
Transaction finalized.

**Actual Result**
Error: The given transaction is not valid due to: TypeError: Cannot read properties of undefined (reading 'split').

**Versions**
- Software Version: 1.4.2

**Comment by shjortConcordium** [comment]
This is an issue with the way we update the wallet for testing, i.e. replacing the files, which can cause the background script and other parts of the wallets to go out of sync.
(Fix is to reload the extension after replacing the files)
