### ISSUE TITLE
Identity proofs check for EU nationality is incorrect

### ISSUE THREAD

**Issue by orhoj** [Concordium/concordium-browser-wallet#443]
**Bug Description**

The function `isEuCountrySet` does not correctly check if the set of countries equals the set of EU members. A list containing a repetition of a single EU member country will also resolve to true when it shouldn't.

**Steps to Reproduce**

Use the proof explorer ([https://web3id-proof-explorer.testnet.concordium.com/](https://web3id-proof-explorer.testnet.concordium.com/)) to generate a set proof where the set is

```
DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK
```

**Expected Result**

The UI should display this as proving that the nationality is in the exact list provided, and thereby not triggering any special EU membership UI.

**Actual Result**

The UI will display this as proving that the nationality is in the EU.

**Versions**

* Software Version: 1.4.2

**Comment by mh-concordium** [comment]
Verified in 1.5.0.
