### ISSUE TITLE
Better error reporting in the browser wallet in case `TokenMetadata` has an invalid `checksum/hash`.

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-browser-wallet#447]
**Description**

When importing the tokens from a contract address into the wallet, and the fetched metadata in the smart contract has a wrongly computed `hash` (or file at the url has changed) for all the tokens, the error returned by the browser wallet is `No valid tokens found in contract`.

Users seem to have difficulties identifying the problem. The problem is a mismatch of the `hash` in the tokenMetadata as stored in the smart contract vs. the freshly computed `hash` from the current file linked in the metadata url. It would be good if the browser wallet could return an error `No valid tokens found in contract. TokenMetadata has an invalid checksum/hash value` similar to the Android wallet.

In addition, some contracts might have both valid and invalid tokens. The browser wallet only shows the valid tokens (a note that some invalid tokens have been found would be useful as well, instead of silently ignoring invalid tokens).

**Steps to Reproduce**
e.g. Contract `8432` has an invalid hash in the token metadata (the contract has only one token). Open the `manage` tab in the browser wallet and try to import the tokens from the contract. Observe the error message. Compare the results with the `AndroidMobileWallet` flow.

e.g. Contract `8418` has some valid and some invalid tokens (wrong hash in metadata). The browser wallet only shows the valid tokens but no message/error/warning that some invalid tokens exist in the contract.

**Comment by Radiokot** [comment]
Mobile wallets now also show "This contract has no valid tokens" if all the tokens are invalid for some reason, including metadata checksum mismatch.
I agree with Doris, that we could add an ability to see the details of contract lookup.
"This contract has no valid tokens" is fine for a regular user, but it gives little help for advanced users or developers. There are many things that could cause a token to be considered invalid, and as an advanced user or a developer, I would like to know the exact cause.

**Comment by abizjak** [comment]
I also think we need to be a bit more pragmatic.

- if there is a single token then we can clearly show the reason why it's not listed
- if there are more tokens we could add  a note, like suggested by @DOBEN, perhaps a small note at the bottom of the list, saying there were invalid tokens found and to see that list if you click on it.
- if the user searches for a specific token and we can find it then we can given them an exact reason why we cannot add the token to the wallet.

**Comment by Radiokot** [comment]
We had a live discussion for this issue and concluded as follows:
- Do not filter out problematic tokens;
- Show problematic tokens in the list with their error messages. In the worst case, it is just an image placeholder, token ID as a name and the error message;
- Do not allow selection of problematic tokens – hide the checkbox;
- Do the same when searching for a token by ID;
- Only if the contract has no tokens at all, do not switch to the tokens list and show "This contract has no tokens" message on the contract index input screen.
