### ISSUE TITLE
While creating a proof we cant select another identity other than first one and its accounts

### ISSUE THREAD

**Issue by bogacyigitbasi** [Concordium/concordium-browser-wallet#453]
**Bug Description**
While generating the proof app allows to pick any account tied to identity 1, but if there are multiple identities and accounts you can't see them.
**Steps to Reproduce**

1. Add another identity and create an account
2. Connect to the platform and click Verify
3. Look for the newly created account
   **Expected Result**

**Actual Result**

**Versions**

* Browser

![Screenshot 2024-04-01 at 13 17 15](https://uploads.linear.app/430cc2b6-6b19-45f6-b7f0-6a0093e10c15/789e78c5-6d1e-4547-873a-b7405ff59e65/6ad60166-3784-481b-85ae-61d4cea565f4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQzMGNjMmI2LTZiMTktNDVmNi1iN2YwLTZhMDA5M2UxMGMxNS83ODllNzhjNS02ZDFlLTQ1NDctODczYS1iNzQwNWZmNTllNjUvNmFkNjAxNjYtMzc4NC00ODFiLTg1YWUtNjFkNGNlYTU2NWY0IiwiaWF0IjoxNzEyMDQxMjA4LCJleHAiOjMzMjgyNjAxMjA4fQ.J4zarsquhIInKjUHK-vx4GD68siaRpWQzdhDGjqccOM "=357x")

![Screenshot 2024-04-01 at 13 17 51](https://uploads.linear.app/430cc2b6-6b19-45f6-b7f0-6a0093e10c15/7f1dcf3e-89b4-4074-8dd1-dc9b5a087aaa/e25b368d-1371-46f8-9211-d6da200f4984?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQzMGNjMmI2LTZiMTktNDVmNi1iN2YwLTZhMDA5M2UxMGMxNS83ZjFkY2YzZS04OWI0LTQwNzQtOGRkMS1kYzliNWEwODdhYWEvZTI1YjM2OGQtMTM3MS00NmY4LTkyMTEtZDZkYTIwMGY0OTg0IiwiaWF0IjoxNzEyMDQxMjA4LCJleHAiOjMzMjgyNjAxMjA4fQ.UgxcrtZE1ruXxfzY8FeBbZ3kO3eLP5nFulxrBoVviug "=1109x")

**Comment by abizjak** [comment]
Are you sure you have more identities that satisfy your request? Because I can see accounts from multiple different identities in the examples I've tried

![image](https://github.com/Concordium/concordium-browser-wallet/assets/105212/adb740c1-3ad9-426c-b8af-cc64ff8bcc49)

**Comment by abizjak** [comment]
Right, but do you actually have any accounts on that identity that satisfy the request?

**Comment by bogacyigitbasi** [comment]
Now I got it, deleting the issue. I can see a valid account from a third identity that satisfies the request. Thank you! 
<img width="365" alt="Screenshot 2024-04-02 at 10 03 52" src="https://github.com/Concordium/concordium-browser-wallet/assets/110228281/b185d98d-a0cb-4c24-9d73-bdb5e1edb28a">
