### ISSUE TITLE
[Wallet API] The script injected into browser applications include WASM

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-browser-wallet#456]
**Bug Description**
This depends on the implementation of https://github.com/Concordium/concordium-node-sdk-js/issues/344. Upgrading the dependency to the common SDK with this change included should fix the issue.

**Steps to Reproduce**

- Go to https://github.com
- Open developer tools (F12)

**Expected Result**
- No WASM compilation error is shown

**Actual Result**
<img width="1425" alt="Screenshot 2024-04-02 at 10 05 00" src="https://github.com/Concordium/concordium-browser-wallet/assets/828403/f60486a5-3b34-4bf9-b0af-81e3dee5c196">

**Versions**
- Software Version: 1.5.1
- OS: macOS
- Browser: chrome

**Comment by limemloh** [comment]
This was solved in https://github.com/Concordium/concordium-browser-wallet/pull/459.
However, the solution is patching the web-sdk, this needs to be solved in the web-sdk somehow instead.
