### ISSUE TITLE
Lags caused by injection script creating WASM instances on every URL change

### ISSUE THREAD

**Issue by Radiokot** [Concordium/concordium-browser-wallet#461]
**Bug Description**

Whenever the page URL changes, the `inject.js` instantiates `WebAssembly`. This causes the tab to quickly run out of memory and start lagging if the URL changes frequently.

**Steps to Reproduce**

- Install Concordium Browser wallet 1.5.1
- Go to Google Maps
- Explore the map: move around, switch modes, watch photos, have a 5-min journey

**Expected Result**

Google Maps remain usable.

**Actual Result**

After lots of URL changes due to moving coordinates and other map activity, the tab goes out of memory and the garbage collector starts using lots of CPU. `Out of memory` errors caused by wallet's `inject.js` are logged into the console. Google Maps become sluggish and unresponsive until the tab is closed or reloaded.
![image](https://github.com/Concordium/concordium-browser-wallet/assets/5675681/5ac9cfc7-0155-459f-ae9c-cd23a401c053)

**Versions**
- Software Version 1.5.1
- OS Windows 11
- Browser Edge 122.0.2365.92 (Official build) (64-bit)

**Comment by abizjak** [comment]
Also reported to happen on [dash.readme.com](http://dash.readme.com/).
