### ISSUE TITLE
Update the browser wallet for cooldown changes

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-browser-wallet#462]
Protocol 7 introduces changes in how stake cooldown is handled.

These need to be reflected in the wallet.

**Comment by DOBEN** [comment]
In addition to the field changes/API changes above, the cooldown changes also relaxed and allowed additional flows while operating an account as a delegated/validator which were previously disallowed.

To support these new flows the text of "running a validator"/"running a delegator" needs to be updated and it needs to be revised which buttons are greyed out (which flows are still disallowed in the protocol 7). Most notable when decreasing your stake A by amount B, you can continue to issue transactions affecting the amount not in cool down (no lock of your remaining staked amount A-B until the cooldown period is over of the stake B in cooldown). This feature was requested by exchanges a lot which preferable use the desktop wallet. Nonetheless, the browser wallet "running a validator"/"running a delegator" flow descriptions should reflect the correct flows possible after protocol 7 update and all wallets should align.

Additional context from the changelog (especially the second bulletpoint)

https://github.com/Concordium/concordium-node/blob/7.0/branch/CHANGELOG.md
```
Changes to stake cooldown behavior in protocol version 7:
- When stake is reduced or removed from a validator or delegator, it becomes inactive, and is not counted for future stake calculations. The inactive stake is not spendable, but is released after a cooldown period elapses.
- Changes to validators and delegators can be made while stake is in cooldown, including changing the stake, or changing directly between validator and delegator.
```
