### ISSUE TITLE
Enable ZK proof generations with new company identities

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-browser-wallet#484]
**Task description**
The browser wallet should support the new company identities concerning ZK proof generation. Three types of proofs exist:

- Reveal attributes ZK proofs:
`webSDK` version 7.5.0 includes changes that allow the revealing of the attributes of the new company identities.

- `SetMemebership/notSetMembership` ZK proofs:
Once the `setMemebership/notSetMembership` in Rust SDK is finalized (approval needed for which attributes to include), update the `webSDK` accordingly as well.

- Range ZK proofs:
No plan to allow them for the company IDs for now.

Task:
Update the `webSDK` in the browser wallet to enable the above proofs generation.

https://support.concordium.software/t/company-id-zk-proofs/1319/8

**Comment by nhs-it** [comment]
Hello - any ETA on this?

**Comment by DOBEN** [comment]
Related PR: https://github.com/Concordium/concordium-browser-wallet/pull/522

**Comment by DOBEN** [comment]
`web-SDK` verison `8.1.0` has been released that supports ZK proof generation:
https://www.npmjs.com/package/@concordium/web-sdk
https://github.com/Concordium/concordium-node-sdk-js/releases/tag/sdk%2Fv
